<h1>Login</h1>
<form method="POST">
	<div style="background-color:red;"><?=$error?></div>
	<div class="form-group">
		<label for="exampleInputEmail1">Email address</label>
		<input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="exampleInputPassword1">Password</label>
		<input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Login</button>
</form>